#!/usr/bin/env bash
# This script displays "Best School" 10 times and Hi once after the 9th best school using if condition

counter=1
while [ $counter -le 10 ]
do
    echo "Best School"
    if [[ "$counter" == '9' ]]
    then
        echo "Hi"
    fi
    ((counter++))
done
