#!/usr/bin/env bash
# This script displays bad luck on the 4th, good luck on the 8th and Best School for the other iterations

counter=1
while [ $counter -le 10 ]
do
    if [[ $counter == '4' ]]
    then
        echo "bad luck"
    elif [[ $counter == '8' ]]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
